#!/usr/bin/env python3

import hashlib
import json
import re
import subprocess
from pathlib import Path
from xml.etree import ElementTree as ET
from zipfile import ZipFile

ROOT = Path(__file__).resolve().parents[1]
XLSX = ROOT / "docs/reference/ThingsforMaking_saju_explanation.xlsx"
DOCX = ROOT / "docs/reference/대운DB_요건서_간략.docx"
JSON_OUT = ROOT / "lib/saju/data/explanation-rules.json"
DOCX_OUT = ROOT / "docs/generated/대운DB_요건서_추출.md"

MAIN_NS = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
REL_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
NS = {"m": MAIN_NS, "r": REL_NS}

FIELD_MAP = {
    "content_id": "id",
    "status": "status",
    "slot": "slot",
    "category": "category",
    "title": "title",
    "trigger_condition": "trigger",
    "saju_basis": "basis",
    "priority": "priority",
    "merge_policy": "mergePolicy",
    "final_section_text": "text",
    "review_status": "reviewStatus",
    "source_sheet": "sourceSheet",
    "source_order": "sourceOrder",
    "theme_match_policy": "matchPolicy",
    "theme_mapping_note": "mappingNote",
    "text_source": "textSource",
}


def file_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def column_index(reference: str) -> int:
    letters = re.match(r"[A-Z]+", reference).group()
    value = 0
    for letter in letters:
        value = value * 26 + ord(letter) - 64
    return value - 1


def read_workbook() -> dict:
    with ZipFile(XLSX) as archive:
        strings = []
        shared = ET.fromstring(archive.read("xl/sharedStrings.xml"))
        for item in shared.findall("m:si", NS):
            strings.append("".join(node.text or "" for node in item.iter(f"{{{MAIN_NS}}}t")))

        workbook = ET.fromstring(archive.read("xl/workbook.xml"))
        relationships = ET.fromstring(archive.read("xl/_rels/workbook.xml.rels"))
        targets = {item.attrib["Id"]: item.attrib["Target"] for item in relationships}
        result = {}

        for sheet in workbook.find("m:sheets", NS):
            name = sheet.attrib["name"]
            relationship_id = sheet.attrib[f"{{{REL_NS}}}id"]
            target = targets[relationship_id].lstrip("/")
            if not target.startswith("xl/"):
                target = f"xl/{target}"
            xml = ET.fromstring(archive.read(target))
            rows = []
            for row in xml.findall(".//m:sheetData/m:row", NS):
                values = {}
                for cell in row.findall("m:c", NS):
                    value_node = cell.find("m:v", NS)
                    value = ""
                    if cell.attrib.get("t") == "s" and value_node is not None:
                        value = strings[int(value_node.text)]
                    elif cell.attrib.get("t") == "inlineStr":
                        value = "".join(
                            node.text or "" for node in cell.iter(f"{{{MAIN_NS}}}t")
                        )
                    elif value_node is not None:
                        value = value_node.text or ""
                    values[column_index(cell.attrib["r"])] = value.replace("\r\n", "\n")
                rows.append(values)

            header_index = next(
                (index for index, row in enumerate(rows) if row.get(0) == "content_id"),
                None,
            )
            if header_index is None:
                continue
            headers = rows[header_index]
            rules = []
            for row in rows[header_index + 1 :]:
                if not row.get(0):
                    continue
                rule = {}
                for index, header in headers.items():
                    target_field = FIELD_MAP.get(header)
                    if not target_field:
                        continue
                    value = row.get(index, "")
                    if target_field in {"priority", "sourceOrder"} and value:
                        value = int(float(value))
                    rule[target_field] = value
                rules.append(rule)
            result[name] = rules

    return {
        "schemaVersion": 1,
        "source": {
            "file": str(XLSX.relative_to(ROOT)),
            "sha256": file_hash(XLSX),
        },
        "themes": result,
    }


def extract_docx() -> None:
    markdown = subprocess.run(
        ["pandoc", "--track-changes=all", str(DOCX), "-t", "gfm"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    preamble = (
        "<!-- Generated by scripts/extract-saju-knowledge.py. Do not edit directly. -->\n"
        f"<!-- Source: {DOCX.relative_to(ROOT)} -->\n"
        f"<!-- SHA-256: {file_hash(DOCX)} -->\n\n"
    )
    DOCX_OUT.parent.mkdir(parents=True, exist_ok=True)
    DOCX_OUT.write_text(preamble + markdown, encoding="utf-8")


def main() -> None:
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(
        json.dumps(read_workbook(), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    extract_docx()


if __name__ == "__main__":
    main()
